export const keyboardInitialState = {
  0: {
    id: 0,
    keyCode: 65,
    freq: 349.23,
    isPressed: false,
    type: 'white',
    letter: 'A',
  },
  1: {
    id: 1,
    keyCode: 87,
    freq: 369.99,
    isPressed: false,
    type: 'black',
    position: 'right',
    letter: 'W',
  },
  2: {
    id: 2,
    keyCode: 83,
    freq: 392.00,
    isPressed: false,
    type: 'white',
    letter: 'S',
  },
  3: {
    id: 3,
    keyCode: 69,
    freq: 415.30,
    isPressed: false,
    type: 'black',
    position: 'middle',
    letter: 'E',
  },
  4: {
    id: 4,
    keyCode: 68,
    freq: 440.00,
    isPressed: false,
    type: 'white',
    letter: 'D',
  },
  5: {
    id: 5,
    keyCode: 82,
    freq: 466.16,
    isPressed: false,
    type: 'black',
    position: 'left',
    letter: 'R',
  },
  6: {
    id: 6,
    keyCode: 70,
    freq: 493.88,
    isPressed: false,
    type: 'white',
    letter: 'F',
  },
  7: {
    id: 7,
    keyCode: 71,
    freq: 523.25,
    isPressed: false,
    type: 'white',
    letter: 'G',
  },
  8: {
    id: 8,
    keyCode: 89,
    freq: 554.37,
    isPressed: false,
    type: 'black',
    position: 'right',
    letter: 'Y',
  },
  9: {
    id: 9,
    keyCode: 72,
    freq: 587.33,
    isPressed: false,
    type: 'white',
    letter: 'H',
  },
  10: {
    id: 10,
    keyCode: 85,
    freq: 622.25,
    isPressed: false,
    type: 'black',
    position: 'left',
    letter: 'U',
  },
  11: {
    id: 11,
    keyCode: 74,
    freq: 659.25,
    isPressed: false,
    type: 'white',
    letter: 'J',
  },
  12: {
    id: 12,
    keyCode: 75,
    freq: 698.46,
    isPressed: false,
    type: 'white',
    letter: 'K',
  },
  13: {
    id: 13,
    keyCode: 79,
    freq: 739.99,
    isPressed: false,
    type: 'black',
    position: 'right',
    letter: 'O',
  },
  14: {
    id: 14,
    keyCode: 76,
    freq: 783.99,
    isPressed: false,
    type: 'white',
    letter: 'L',
  },
  15: {
    id: 15,
    keyCode: 80,
    freq: 830.61,
    isPressed: false,
    type: 'black',
    position: 'middle',
    letter: 'P',
  },
  16: {
    id: 16,
    keyCode: 186,
    freq: 880.00,
    isPressed: false,
    type: 'white',
    letter: ';',
  },
  17: {
    id: 17,
    keyCode: 219,
    freq: 932.33,
    isPressed: false,
    type: 'black',
    position: 'left',
    letter: '[',
  },
  18: {
    id: 18,
    keyCode: 222,
    freq: 987.77,
    isPressed: false,
    type: 'white',
    letter: ',',
  },
  19: {
    id: 19,
    keyCode: 90,
    freq: 1046.50,
    isPressed: false,
    type: 'white',
  },
  20: {
    id: 20,
    keyCode: 221,
    freq: 1108.73,
    isPressed: false,
    type: 'black',
    position: 'right',
  },
  21: {
    id: 21,
    keyCode: 88,
    freq: 1174.66,
    isPressed: false,
    type: 'white',
  },
  22: {
    id: 22,
    keyCode: 220,
    freq: 1244.51,
    isPressed: false,
    type: 'black',
    position: 'left',
  },
  23: {
    id: 23,
    keyCode: 67,
    freq: 1318.51,
    isPressed: false,
    type: 'white',
  },
};
